site_name: BES Playbook
theme:
  name: null
  custom_dir: 'bes-theme'
  navigation_depth: 2
markdown_extensions:
  - attr_list
plugins:
  - search
nav:
  - Home: index.md
  - Styleguide: styleguide.md
  - Automated Testing:
    - 1. Overview: testing/1-1-testing.md
  - User Experience:
    - 1. Overview:
      - 1.1 Purpose:  ux/1-1-purpose.md
      - 1.2 Audience: ux/1-2-audience.md
      - 1.3 Benefits of UX: ux/1-3-benefits.md
      - 1.4 Levels of Design Maturity: ux/1-4-maturity.md
    - 2. User Experience:
      - 2.1 What is UX?: ux/2-1-what-is-ux.md
      - 2.2 UX Disciplines & Project Roles: ux/2-2-disciplines.md
      - 2.3 UX in Software Lifecycle Methodologies: ux/2-3-lifecycle.md
    - 3. UX Principles & Methodology:
      - 3.1 UX Principles: ux/3-1-principles.md
      - 3.2 UX Methodology: ux/3-2-methodology.md
    - 4. Web Design Standards:
      - 4.1 Introduction: ux/4-1-introduction.md

extra:
  playbooks:
    Automated Testing: testing/1-1-testing
    User Experience: ux/1-1-purpose
  footer:
    AFLCMC/BES:
      Air Force Life Cycle Management Center (AFLCMC): http://google.com
      Air Force Business and Enterprise Systems (BES): http://google.com


