site_name: BES Playbook
theme:
  name: null
  custom_dir: 'bes-theme'
  navigation_depth: 2
markdown_extensions:
  - attr_list
  - extra
plugins:
  - search
nav:
  - Home: index.md

extra:
  # Update the baseurl for the location of deployment.
  # This value is combined with the playbook urls to build the inter-playbook nav
  # baseurl: https://isobar-us.github.io/USAF-2212-A4UX-Playbook
  baseurl: https://ArrayBESPlaybooks.github.io/ArrayBESPlaybook
  # baseurl: http://localhost:8000

  # This list
  playbooks:
    - name: Agile
      url: /agile/1-1-purpose
      icon: _assets/0_home_page_icon_agile.svg
      desc: Faster, more dynamic response to customers’ development needs requires a modern management approach. Learn what is necessary to establish those responsive process and management guidelines within the DoD environment.
    - name: Automated Testing
      url: /testing/1-1-purpose
      icon: _assets/0_home_page_icon_automatedtesting.svg
      desc: With the move towards more flexible approaches to software development comes the desire to implement faster, more reliable testing procedures. Learn practical, experienced-based methods and best practices for automating testing.
    - name: User Experience
      url: /ux/1-1-purpose
      icon: _assets/0_home_page_icon_user_experience.svg
      desc: Delivering value requires delivering an experience that meets the needs of your users. Learn what UX is, how it benefits and enhances development efforts, methods for designing experiences, and best-practice visual design guidelines.
    - name: Automated Application Modernization (in progress)
      url: /modern/1-1-play-1
      icon: _assets/0_home_page_icon_automated_App_modern.svg
    - name: Low-Code (in progress)
      url: /low-code/1-1-plays
      icon: _assets/0_home_page_icon_agile_Model-Driven.svg
    # - name: DevSec Ops
    #   url: /devops/1-1-devops
    #   icon: _assets/0_home_page_icon_devsec.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium, dolor ex scelerisque purus.
    # - name: Cyber Security
    #   url: /cyber/1-1-cyber
    #   icon: _assets/0_home_page_icon_security.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium.
    # - name: App Technology Refresh for Cloud
    #   url: /cloud/1-1-cloud
    #   icon: _assets/0_home_page_icon_cloud.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium, dolor ex scelerisque purus, id ornare lectus. purus non justo.
    # - name: Agile Acquistions
    #   url: /acquistions/1-1-acquistions
    #   icon: _assets/0_home_page_icon_agile_acquistions.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium, dolor ex scelerisque purus, id ornare lectus.

  footer:
    AFLCMC/BES:
      Air Force Life Cycle Management Center (AFLCMC): https://www.wpafb.af.mil/aflcmc
      Air Force Business and Enterprise Systems (BES): https://www.airforcebes.af.mil

  section_headers:
    - ../../_assets/_headers/Header01.jpg
    - ../../_assets/_headers/Header02.jpg
    - ../../_assets/_headers/Header03.jpg
    - ../../_assets/_headers/Header04.jpg
    - ../../_assets/_headers/Header05.jpg
    - ../../_assets/_headers/Header06.jpg
    - ../../_assets/_headers/Header07.jpg
    - ../../_assets/_headers/Header08.jpg
    - ../../_assets/_headers/Header09.jpg
  home_headers:
    - _assets/0_home_page_header_01@2x.jpg
    - _assets/0_home_page_header_02@2x.jpg
    - _assets/0_home_page_header_03@2x.jpg
    - _assets/0_home_page_header_04@2x.jpg
