site_name: BES Playbook
theme:
  name: null
  custom_dir: 'bes-theme'
  navigation_depth: 2
markdown_extensions:
  - attr_list
  - admonition
  - extra
plugins:
  - search
nav:
  - Home: index.md
  - Styleguide: styleguide.md
  - Automated Testing:
    - 1. Overview: testing/1-1-testing.md
  - User Experience:
    - 1. Overview:
      - 1.1 Purpose:  ux/1-1-purpose.md
      - 1.2 Audience: ux/1-2-audience.md
      - 1.3 Benefits of UX: ux/1-3-benefits.md
      - 1.4 Levels of Design Maturity: ux/1-4-maturity.md
    - 2. User Experience:
      - 2.1 What is UX?: ux/2-1-what-is-ux.md
      - 2.2 UX Disciplines & Project Roles: ux/2-2-disciplines.md
      - 2.3 UX in Software Lifecycle Methodologies: ux/2-3-lifecycle.md
    - 3. UX Principles & Methodology:
      - 3.1 UX Principles: ux/3-1-principles.md
      - 3.2 UX Methodology: ux/3-2-methodology.md
      - 3.3 subpages:
        - Interviews: ux/3-3-1-1-interviews.md
        - Surveys: ux/3-3-1-2-surveys.md
        - Site metrics analysis: ux/3-3-1-3-metrics.md
        - Diary studies: ux/3-3-1-4-diary.md
        - Personas: ux/3-3-2-1-personas.md
        - User Scenarios: ux/3-3-2-2-scenarios.md
        - Journey maps: ux/3-3-2-3-journey.md
        - Service design blueprints: ux/3-3-2-4-blueprints.md
        - Use cases: ux/3-3-2-5-usecase.md
      - "3.3 Phase 1: Research & Discovery": ux/3-3-research.md
      - 3.4 subpages:
        - Wireframing/sketching: ux/3-4-1-1-wireframe.md
        - Information architecture: ux/3-4-1-2-ia.md
        - Participatory design: ux/3-4-1-3-participatory.md
        - Concept testing: ux/3-4-1-4-concept.md
        - Roadmapping: ux/3-4-2-1-roadmapping.md
        - Story writing: ux/3-4-2-2-story.md
      - "3.4 Phase 2: Conceptual Design": ux/3-4-conceptual.md
      - 3.5 subpages:
        - High-fidelity wireframing and visual design: ux/3-5-1-1-visualdesign.md
        - Prototyping: ux/3-5-1-2-prototyping.md
        - Usability testing: ux/3-5-1-3-usability.md
        - Specifying/annotating: ux/3-5-1-4-annotating.md
      - "3.5 Phase 3: Detailed Design": ux/3-5-detailed.md
      - "3.6 Phase 4: Support": ux/3-6-support.md
    - 4. Web Design Standards:
      - 4.1 Introduction: ux/4-1-introduction.md
      - 4.2 General Interface Guidelines: ux/4-2-guidelines.md
      - 4.3 Grids & Breakpoints: ux/4-3-grids.md
      - 4.4 Branding/Logo: ux/4-4-branding.md
      - 4.5 Global Headers & Footers: ux/4-5-headers.md
      - 4.6 Page Layouts: ux/4-6-layouts.md
      - 4.7 Typography: ux/4-7-typography.md
      - 4.8 Color: ux/4-8-color.md
      - 4.9 Iconography: ux/4-9-icons.md
      - 4.10 Imagery: ux/4-10-imagery.md
      - 4.11 Buttons & Controls: ux/4-11-buttons.md
      - 4.12 Key Mobile Standards: ux/4-12-mobile.md
      - 4.13 Accessibility: ux/4-13-accessibility.md
extra:
  playbooks:
    - name: Agile
      url: ux/1-1-purpose
      icon: /img/agile.svg
      desc: Faster, more dynamic response to customers’ development needs requires a modern management approach. Learn what is necessary to establish those responsive process and management guidelines within the DoD environment.
    - name: Automated Testing
      url: testing/1-1-testing
      icon: /img/agile.svg
      desc: With the move towards more flexible approaches to software development comes the desire to implement faster, more reliable testing procedures. Learn practical, experienced-based methods and best practices for automating testing.
    - name: User Experience
      url: ux/1-1-purpose
      icon: /img/agile.svg
      desc: Delivering value requires delivering an experience that meets the needs of your users. Learn what UX is, how it benefits and enhances development efforts, methods for designing experiences, and best-practice visual design guidelines.
  footer:
    AFLCMC/BES:
      Air Force Life Cycle Management Center (AFLCMC): http://google.com
      Air Force Business and Enterprise Systems (BES): http://google.com


